name: Deploy docs

on:
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate microsite
      run: |
        brew tap bow-swift/nef
        brew install sourcekitten
        brew install nef
        gem install bundler -v 2.0.2
        gem install cocoapods -v 1.8.4
        ./scripts/gen-docs.rb
    - name: Deploy microsite
      uses: peaceiris/actions-gh-pages@v3
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_GH_PAGES_BOW }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./gen-docs
