name: Deploy docs

on:
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate microsite
      run: |
        brew tap bow-swift/nef
        brew install sourcekitten
        brew install nef
        gem install bundler -v 2.0.2
        gem install cocoapods -v 1.8.4
        ./scripts/gen-docs.rb
    - name: Deploy microsite
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./pub-dir
