name: Compile and test

on: [pull_request]

jobs:
  macos:
    name: macos | Compile and test
    runs-on: macos-latest
    env:
      XCODE_VERSION: ${{ '11.4.1' }}

    steps:
    - uses: actions/checkout@v2
    - name: Switch Xcode version
      run: "sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app"
    - name: Generate linux tests
      run: swift test --generate-linuxmain
    - name: Cached auto-generate linux tests
      uses: actions/upload-artifact@v1
      with:
        name: generate-linuxmain
        path: Tests
    - name: Run tests
      run: swift test

  linux:
    name: linux | Compile and test
    needs: macos
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clean Tests
      run: rm -rf Tests
    - name: Get auto-generate linux tests
      uses: actions/download-artifact@v1
      with:
        name: generate-linuxmain
        path: Tests
    - name: Run tests
      run: swift test
    - name: Remove generated artifact
      uses: geekyeggo/delete-artifact@v1
      with:
        name: generate-linuxmain
        failOnError: false
